STATE_FILE = "commander_state.json"
CPU_LOG_FILE = "commander_cpu.log"
TERMINAL_REFRESH_SECONDS = 3
INDEX_WATCHLIST = {
    "NIFTY": "NSE:NIFTY50-INDEX",
    "BANKNIFTY": "NSE:NIFTYBANK-INDEX",
    "SENSEX": "BSE:SENSEX-INDEX",
    "NIFTYIT": "NSE:NIFTYIT-INDEX",
    "PSUBANK": "NSE:NIFTYPSUBANK-INDEX",
    "INDIAVIX": "NSE:INDIAVIX-INDEX",
}
CASH_WATCHLIST = {
    "RELIANCE": "NSE:RELIANCE-EQ",
    "HDFCBANK": "NSE:HDFCBANK-EQ",
    "ICICIBANK": "NSE:ICICIBANK-EQ",
    "TCS": "NSE:TCS-EQ",
    "INFY": "NSE:INFY-EQ",
    "ITC": "NSE:ITC-EQ",
    "TATASTEEL": "NSE:TATASTEEL-EQ",
    "NMDC": "NSE:NMDC-EQ",
    "VEDL": "NSE:VEDL-EQ",
    "HINDZINC": "NSE:HINDZINC-EQ",
}
OPTION_INDEXES = {
    "1": ("NIFTY", "NSE:NIFTY50-INDEX"),
    "2": ("BANKNIFTY", "NSE:NIFTYBANK-INDEX"),
    "3": ("SENSEX", "BSE:SENSEX-INDEX"),
}
